// <auto-generated />
namespace ShareDeployed.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201211291513121_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVX227TQBB9R+IfrH2CB7KhSIhWDqikLYogLcKF94k9TlfsxXjXVfJtPPBJ/AKz8SWunSuXB97i8VzOnJ2z4/z8/iN8s1AyuMfcCqNH7PlgyALUsUmEno9Y4dJnr9ib148fhZeJWgRfar8T70eR2o7YnXPZGec2vkMFdqBEnBtrUjeIjeKQGH4yHL7iz4ccKQWjXEEQfiq0EwpXD/Q4NjrGzBUgpyZBaSs7vYlWWYNrUGgziHHEojvI8QIzaZaYDEp/FpxLAYQlQpkeCWx46oGxpiQVvSRwbnm7zHBVeMQ+W8w/5iYVEtuO5Poelw8MZCLHDHO3/IRpK3ySsIA/jOXd4Ca0E+eRjNhEuxcnLLgupISZJEMK0iILspdnkTM5vkONOThMPoJzmNMpTRJcdVIxcpa9PIyUUz488aRw0No4cHTkPfAboPpfNdjI5TRBLLgSC0w+oJ67uwbwFBa1hX6y4LMWNHAU5PIC2w2Wz7sLXyoQ8h9XDfl6IvpzQsPrQBD3LSqsN+LCdaalDIjQ9eeKZnhdpBzkQXvsNgJqSq8Fw0vF1MriW6QVTiHLiKuW1CpLEJU6Gz+LjleSKnPw2G4QVIO2qURjC3PsvKXShPRK5NZdgIMZ+NMbJ6rndgjRdakNfHd1u6a/DvK/y8BNl85g663QpvOKOlQkw1Wz2ODacadU8VEMEvItN8LYyELpXbfLviylWLt5SuvhmSr1tdNUpn6OkHco6R4A751A577snuouRXRdmuqNMjoKCKtp3L+BeuNZurCAyLkXiR/NaGkdqoF3GETf5FgK6nftMAUtUrTu1nxFv01JPb+/wprb2tpE/gd7THgm9m6s3po7bv/oe8hjEu0TBYunf7RTjsh03J7o33IHL4t9u6IcyBFLZobaKOH+jWXSl0jI259y4QVaMV+n8B92GmP/AbFOWvtMdGpq4qnLNqLapXMuU3SQEFnnuRMpxI5ex2jtauV/AVmsjm6GyUTfFC4r3Lm1qGZy2e435LvrrzbmQ8zhTeaf7N9ogWAKagFv9NtCyKTBfdUf8m0p/NxUyiFU9MlD6ebLJtO10QcmquijtYba6+4WVSYpmb3REdzjdmz7OXzIWHghYJ6DajNYWiokEVDlVgkq0I5Y1/P/RLj/K/L6FwxYXc+8DAAA"; }
        }
    }
}
