// <auto-generated />
namespace ShareDeployed.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209211917124_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1ZzW7bOBC+L7DvIOi0e6jlZoEiDeQWqZMsgq2TIEp7p6WxQyx/VJEy7GfrYR9pX2GH+jMl+Udau2la5GJIQ843w+E31HD879d//PdLzpwFJIpKMXJfD4auAyKUERXzkZvq2atT9/27X3/xLyO+dD6X807MPNQUauQ+ah2feZ4KH4ETNeA0TKSSMz0IJfdIJL2T4fDUez30ACFcxHIc/z4VmnLIXvB1LEUIsU4Jm8gImCrkOBJkqM4N4aBiEsLIDR5JAhcQM7mCaHBBNHGdc0YJehIAm/V0a/jWuOVWBtHkJbqmVw+rGDKzI/ceFiBSsCfhtL9gVROg6C6RMSR6dQ+zQvU6ch2vruc1FSs1S8dYxyeh/zhxnZuUMTJlKJgRpsB14jdngZYJ/AkCEqIhuiNaQyKMLmTeF1E4i990C8Rbb3hiAuERIaQmGje55XjDzU8Kkv2u7sYwvyVCoBPknOtc0SVEH0HM9WOFMiHLUoKPrvNJUKQoKukE96Wv1Qe6tor8gfy9J8g5l8jhCgZCyglznbsEn4pcOnWdICQGsX9kLkCFCY3zjThigPJ327bvrQm/Mw0ulzEI9ZIGL2nwdGlwre7hS0oTqCL8QUoGRPwMCWWo85JNzyATPsq5FEc33ZcZWARpQjH4hVe1QscMwlI36JIrBqAblYqztpNXRYNqxNuNUB7ybYRqZA9Cxuq2ei7eFI1q3euqz8vLvrI89LbUh/6ExDFulFUvFhInyIvF8augf0HIcwwvVBvqwsrbyhImDZlDYxRNo6dXNFHalKhTYiI3jnhrWp9dLk3uKEtr50w53zxv4FRWPA+2wKxjeYXL43gCZCuFypmtDmS65sQnyYZDaCxZysW2g2yXdvmltRFKWXeUPM1tjFzSHSH/TtoIuaQ7QvnRtDFKWXeU2hfNhqoNtPF8r7GxTQJ5LQY1PjZNQnai68bysT9dt8B0oOtWzRe67kY4Dl3tUq4WVUv+05K/Xer1Z/4mjA6036z2bTh/OFutUsyGscRPvKetKqU5pbJeVSuNqsQvKoT9ra1WyZBPMdcpuaBRVi6slAaeEyL4wsaMgknDcsKECDoDpR/k32DadFjR/P/uWFW/KxWxZ9oio2b1e+8tPe8D9Tt9ZuKAG71YkCTEdP6Nk+XvB93SI1yePvyWHj1Bs2rron/EBtQLyZ4BydqtoCntH7Mnour3ae18E54ej2WtNsvRIt9snbTv3gf3TfJPMfJ6KtH93M1iUB2jq7IJvxjcj7+z57IJ2YyozRHu0I5pFzS+Z/+j52OW0fkawvy/JyA0SbcGLedci5ksiYIrsj0qpzR4NAFN8JQi54mmMxJqHA5Bqaxj95mw1ESOTyG6FrepjlN9rhTwKVvZ6/W93faznlPdZ/82OzbUMZaAblJz0N6KDyllUeX3VTuPtkEYjhdpjl4F2qT7fFUh3UjREagIH142QJhD4gF4zBBM3YqALGC7b/tjWI+Yf0HJPCHcjmAuKTueBC1bJtCArbG2h69I14gv3/0HAGVvG8MeAAA="; }
        }
    }
}
